/*
 * This file was generated by the Gradle 'init' task.
 */
group = "me.altzenck"
version = "1.2.0"
description = "Yml"

plugins {
    kotlin("jvm") version "1.9.22"
    `maven-publish`
    id("com.github.johnrengelman.shadow") version ("8.1.1")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenLocal()
    maven("https://jitpack.io")
    maven("https://repo.maven.apache.org/maven2/")
    flatDir {
        dirs = setOf(file("libs"))
    }
}

dependencies {
    implementation("com.github.Altzenck:IOUtils:-SNAPSHOT")
    implementation("org.yaml:snakeyaml:2.2")
    implementation("com.google.code.findbugs:jsr305:3.0.2")
    implementation(kotlin("stdlib-jdk8"))
}

tasks {
    shadowJar {
        dependencies {
            include(dependency("com.github.Altzenck:IOUtils:-SNAPSHOT"))
        }
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
