/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.github.johnrengelman.shadow") version ("8.1.1")
}

repositories {
    mavenLocal()
    maven("https://jitpack.io")
    maven("https://repo.maven.apache.org/maven2/")
    flatDir {
        dirs = setOf(file("libs"))
    }
}

dependencies {
    implementation("com.github.Altzenck:IOUtils:-SNAPSHOT")
    implementation("org.yaml:snakeyaml:2.2")
    implementation("com.google.code.findbugs:jsr305:3.0.2")

}

tasks {
    shadowJar {
        dependencies {
            include(dependency("com.github.Altzenck:IOUtils:-SNAPSHOT"))
        }
    }
}

group = "me.altzenck"
version = "1.2.0"
description = "Yml"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
