/*
 * This file was generated by the Gradle 'init' task.
 */
group = "me.altzenck"
version = "2.0.0-SNAPSHOT"
description = "Yamsu"

plugins {
    kotlin("jvm") version "1.9.22"
    `maven-publish`
    id("com.github.johnrengelman.shadow") version ("8.1.1")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenLocal()
    maven("https://jitpack.io")
    maven("https://repo.maven.apache.org/maven2/")
    flatDir {
        dirs = setOf(file("libs"))
    }
    //maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
}

dependencies {
    implementation("com.github.Altzenck:IOUtils:master-SNAPSHOT")
    implementation("org.yaml:snakeyaml:2.2")
    implementation("com.google.code.findbugs:jsr305:3.0.2")
    //compileOnly("org.spigotmc:spigot-api:1.21-R0.1-SNAPSHOT")
    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")
}

tasks {

    jar {
        enabled = false
    }

    shadowJar {
        destinationDirectory.set(File(projectDir, "./build/libs"))
        archiveFileName.set(jar.get().archiveFileName)
        dependencies {
            include(dependency("com.github.Altzenck:IOUtils:master-SNAPSHOT"))
        }
    }

    build {
        dependsOn(shadowJar)
    }
}

publishing {
    publications{
        create<MavenPublication>("maven") {
           from(components["java"])
           groupId = project.group.toString()
           artifactId = project.name
           version = project.version.toString()
           artifact("build/libs/${project.name}-${project.version}.jar")
        }
    }
}
